# services.yaml

parameters:
    images_directory: '%kernel.project_dir%/public/images'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Injection automatique des dépendances dans vos services
        autoconfigure: true # Enregistrement automatique des services comme commandes, abonnés aux événements, etc.

    # Service pour écouter les exceptions et rediriger les erreurs 404
    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 10 }

    App\Security\UserChecker:
        tags:
            - { name: 'security.user_checker' }

    App\EventListener\UserChecker:
        tags:
            - { name: 'security.user_checker' }

    # services pour les autres classes de votre application
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

